#!/bin/sh

# Verify all .java files compile prior to checkin.
./gradlew --console=plain -PcfLocal compileJava compileTestJava

# Don't check code formatting here; it is run as part of `gradlew check`.
